### PR TITLE
Changes privates variables to protected allowing extend the class

### PR DESCRIPTION
**Pull request by jmarcelocjr**
I've changed the vars $securitySalt, $bbbServerBaseUrl, $urlBuilder from private to protected to allow extend the class and change the construct

### CODE REVIEW

**Comment by GhaziTriki** [comment]
@jmarcelocjr The idea behind making them private is make sure that the developer never exposes those variables in the source code, they should be configured in the environment variables. Can you please give a use case why are they needed in a subclass?

**Comment by jmarcelocjr** [comment]
captura de tela de 2016-12-20 17-01-32

The company that i work has more than one bigbluebutton server, and I need to override the construct to allow me to pass the server and the salt by parameters instead of environment vars.

And if the attributes are private I can't do this, because I can't access them, changing them to protected they'll continue been protected from outside, only child's will be able to access them

**Comment by GhaziTriki** [comment]
If you take a look at those lines https://github.com/bigbluebutton/bigbluebutton-api-php/blob/master/src/BigBlueButton.php#L56-L57 you will see that we want to avoid what have wrote in the first two lines of your constructor.

**Comment by jmarcelocjr** [comment]
I'd see that, but I have more than one bigbluebutton server with different hosts and salts, so it won't be possible if the data are in environments vars.

The host and the salt are in an file that are separated from the source code. And I just get the data and send them to API.

captura de tela de 2016-12-20 17-28-21

**Comment by jmarcelocjr** [comment]
@GhaziTriki there's no way to this be accepted? Because the format that the API works today (expecting only one bigbluebutton server) it won't work in my case.
Maybe another workaround? To allow more than one bbb server

**Pull request merged**
