### PR TITLE
Add guestPolicy param

### PR DESCRIPTION
**Pull request by rustamwin**

### CODE REVIEW

**Comment by rustamwin** [comment]
ping @GhaziTriki

**Comment by iflorespaz** [comment]
Why this is not merged?

**Comment by Yurujai** [comment]
Hi,

I made another PR to fix this.
See https://github.com/bigbluebutton/bigbluebutton-api-php/pull/67

I hope it's ok.

**Comment by GhaziTriki** [comment]
@iflorespaz We are busy making the main product better 😉

**Comment by andreasotto** [comment]
+1 please merge

**Pull request merged**
