### PR TITLE
Fix some tests

### PR DESCRIPTION
**Pull request by Yurujai**
I fixed some tests, changes are:

`
->setLockSettingsLockOnJoinConfigurable($params['lockSettingsLockOnJoinConfigurable'])
`

instead of 

`
->setLockSettingsLockOnJoinConfigurable($params['lockSettingsLockOnJoin'])
`

and added

`
 ->addMeta('bbb-recording-ready-url', $params['meta_bbb-recording-ready-url']);
`

### CODE REVIEW

**Comment by GhaziTriki** [comment]
@Yurujai I think you replaced a parameter with a new one, as you see both of `lockSettingsLockOnJoinConfigurable` and `lockSettingsLockOnJoin` exists:

https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-web/grails-app/conf/bigbluebutton.properties#L344-L345

**Comment by GhaziTriki** [comment]
However the fix for `meta_bbb-recording-ready-url` seems to be correct. Could you please make a separate PR for it?

**Comment by Yurujai** [comment]
Hi @GhaziTriki,

I replaced parameter because its using wrong parameter.

As you can see on https://github.com/bigbluebutton/bigbluebutton-api-php/blob/master/tests/TestCase.php#L137, both methods are using the same parameter value (lockSettingsLockOnJoin).

I changed that because if we are configuring "lockSettingsLockOnJoinConfigurable" we need to use "lockSettingsLockOnJoinConfigurable" param.

Thanks!

**Comment by Yurujai** [comment]
> However the fix for `meta_bbb-recording-ready-url` seems to be correct. Could you please make a separate PR for it?

I created a new PR with "meta_bbb-recording-ready-url" change: https://github.com/bigbluebutton/bigbluebutton-api-php/pull/79

Thanks!

**Comment by GhaziTriki** [comment]
@Yurujai Please make sure to use the formatter as documented in the README.

**Comment by GhaziTriki** [comment]
@Yurujai This is a valid PR. Thank you.

**Pull request merged**
