### PR TITLE
make XML Response timeout to be configurable

### PR DESCRIPTION
**Pull request by Kaabi**
Customize XML Response Timeout, in my case I like to adjust it to 2ms instead of your default 10ms

### CODE REVIEW

**Comment by GhaziTriki** [comment]
@Kaabi Can you keep the property protected and add an accessor?

**Comment by Kaabi** [comment]
Hello @GhaziTriki check now a0ad748

**Comment by GhaziTriki** [comment]
Thanks @Kaabi but you forgot to push it to this PR.

**Comment by Kaabi** [comment]
@GhaziTriki check now

**Pull request merged**
