### PR TITLE
Update BigBlueButton.php

### PR DESCRIPTION
**Pull request by rebootcode**
Adding shareable or dynamic constructor for secret and server URL.

### CODE REVIEW

**Comment by rebootcode** [comment]
This is very important to have BigBlueButton settings changed on runtime.

**Comment by rebootcode** [comment]
@simsek97 - I can't see the changes here - https://github.com/bigbluebutton/bigbluebutton-api-php/blob/master/src/BigBlueButton.php#L63

**Comment by DariuszWalkiewicz** [comment]
Like this? Yes, please - its very usefull when you use more that one bare metal server.

`public function __construct($securitySecret = null, $bbbServerBaseUrl = null)
    {
        // Keeping backward compatibility with older deployed versions
        // $this->securitySecret = (getenv('BBB_SECURITY_SALT') === false) ? getenv('BBB_SECRET') : $this->securitySecret = getenv('BBB_SECURITY_SALT');
        // $this->bbbServerBaseUrl = getenv('BBB_SERVER_BASE_URL');
        if ($securitySecret === null) {
            $this->securitySecret = (getenv('BBB_SECURITY_SALT') === false) ? getenv('BBB_SECRET') : $this->securitySecret = getenv('BBB_SECURITY_SALT');
        } else {
            $this->securitySecret = $securitySecret;
        }
        if ($bbbServerBaseUrl === null) {
            $this->bbbServerBaseUrl = getenv('BBB_SERVER_BASE_URL');
        } else {
            $this->bbbServerBaseUrl = $bbbServerBaseUrl;
        }
        $this->urlBuilder = new UrlBuilder($this->securitySecret, $this->bbbServerBaseUrl);
    }`

**Comment by GhaziTriki** [comment]
This is finally doable https://github.com/bigbluebutton/bigbluebutton-api-php/commit/706ecf5e69aad4fe00be7e6715b120c0dbb62c40

**Pull request closed without merging**
