### PR TITLE
declare the expected instance on createMeeting

### PR DESCRIPTION
**Pull request by goldsky**

### CODE REVIEW

**Comment by GhaziTriki** [comment]
@goldsky it is dillema whether to use phpdoc or type hinting in the signautres. Why should we add type hinitng while the phpdoc does the expected job?

Can you please create another pull request to improve the .gitignore file?

**Comment by GhaziTriki** [comment]
We will stay on phpdocs.

**Comment by goldsky** [comment]
The problem is that it gives a mislead example.
https://github.com/goldsky/bigbluebutton-api-php/blob/6eca18802585bf2832abc2106c1d1f6379de36d0/src/BigBlueButton.php#L273

**Comment by goldsky** [comment]
It confused me at the first time, as well

**Pull request closed without merging**
